# Generated by Django 6.0.2 on 2026-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_knowledgeitem_uploaded_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='custom_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
