# Generated by Django 5.2.11 on 2026-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_knowledgeitem_custom_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
