# Generated by Django 5.2.11 on 2026-02-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='category',
        ),
    ]
